// GENERATED by tool/gen_tokens.dart from design/system/project/tokens.json.
// Do not edit by hand.
import 'package:flutter/material.dart';

@immutable
class PbColors extends ThemeExtension<PbColors> {
  const PbColors({
    required this.ground,
    required this.glow1,
    required this.glow2,
    required this.glow3,
    required this.glass,
    required this.glassStrong,
    required this.glassLine,
    required this.surface,
    required this.sunken,
    required this.ink,
    required this.inkMuted,
    required this.line,
    required this.lineStrong,
    required this.accent,
    required this.onAccent,
    required this.accentText,
    required this.success,
    required this.warning,
    required this.danger,
    required this.scrim,
  });

  static const dusk = PbColors(
    ground: Color(0xFF1B1114),
    glow1: Color(0xFFFF6A45),
    glow2: Color(0xFFC43D68),
    glow3: Color(0xFFFFB23E),
    glass: Color(0x9926161A),
    glassStrong: Color(0xBD221418),
    glassLine: Color(0x2EFFE2CE),
    surface: Color(0xFF2A1A1E),
    sunken: Color(0x1AFFF4EC),
    ink: Color(0xFFFFF4EC),
    inkMuted: Color(0xFFD9C4BA),
    line: Color(0x1FFFF4EC),
    lineStrong: Color(0x6BFFF4EC),
    accent: Color(0xFFFFAB52),
    onAccent: Color(0xFF2B1503),
    accentText: Color(0xFFFFAB52),
    success: Color(0xFF8FE3AD),
    warning: Color(0xFFFFC566),
    danger: Color(0xFFFFA093),
    scrim: Color(0x8F000000),
  );

  static const dawn = PbColors(
    ground: Color(0xFFFBEEE8),
    glow1: Color(0xFFFF9F80),
    glow2: Color(0xFFF7A8C4),
    glow3: Color(0xFFFFD27A),
    glass: Color(0x80FFFFFF),
    glassStrong: Color(0xB8FFFFFF),
    glassLine: Color(0xD9FFFFFF),
    surface: Color(0xFFFFF7F3),
    sunken: Color(0x122A1418),
    ink: Color(0xFF2A1418),
    inkMuted: Color(0xFF553739),
    line: Color(0x1F2A1418),
    lineStrong: Color(0x662A1418),
    accent: Color(0xFFFF9838),
    onAccent: Color(0xFF2B1503),
    accentText: Color(0xFFA33A08),
    success: Color(0xFF1A6B3C),
    warning: Color(0xFF8A4700),
    danger: Color(0xFFB3261E),
    scrim: Color(0x5C2A1418),
  );

  /// Фон экрана под светом и стеклом.
  final Color ground;

  /// Первое пятно света за стеклом: коралл. Крупный размытый круг в верхнем левом углу экрана. Текст прямо на свет не кладётся — только через стекло.
  final Color glow1;

  /// Второе пятно света: малина на закате, роза на рассвете. Справа, в средней трети экрана.
  final Color glow2;

  /// Третье пятно света: янтарь. Внизу экрана, под панелью ввода.
  final Color glow3;

  /// Основной материал. Карточки упражнений, строки списков, плашки. Всегда с размытием glass-blur и кромкой glass-line.
  final Color glass;

  /// Плотное стекло под крупными цифрами и вводом: панель ввода результата, шторки, панель вкладок, текущее упражнение.
  final Color glassStrong;

  /// Кромка стекла толщиной 1 px.
  final Color glassLine;

  /// Непрозрачная замена стекла там, где размытие недоступно или тормозит (слабые Android).
  final Color surface;

  /// Утопленные элементы на стекле: степперы, незаполненные блины, подложка активной вкладки.
  final Color sunken;

  /// Основной текст и цифры факта на glass, glass-strong и surface.
  final Color ink;

  /// Вторичный текст, цифры плана и единицы измерения на glass, glass-strong и surface.
  final Color inkMuted;

  /// Декоративные разделители. Смысла не несут.
  final Color line;

  /// Гриф и контуры, которые несут смысл: невыполненный блин, рамка поля.
  final Color lineStrong;

  /// Янтарная заливка главного действия и выполненных блинов. Одна залитая кнопка на экран.
  final Color accent;

  /// Текст и иконки поверх заливки accent.
  final Color onAccent;

  /// Акцент как текст и контур на стекле: текстовые кнопки, активная вкладка, обводка текущего упражнения и текущего блина.
  final Color accentText;

  /// Факт не ниже плана. Всегда со словом или знаком.
  final Color success;

  /// Факт ниже плана; запись ещё не отправлена. Всегда со словом или знаком.
  final Color warning;

  /// Ошибки и необратимые действия. Всегда со словом.
  final Color danger;

  /// Затемнение экрана под шторкой и диалогом.
  final Color scrim;

  @override
  PbColors copyWith() => this;

  @override
  PbColors lerp(PbColors? other, double t) {
    if (other == null) return this;
    return PbColors(
      ground: Color.lerp(ground, other.ground, t)!,
      glow1: Color.lerp(glow1, other.glow1, t)!,
      glow2: Color.lerp(glow2, other.glow2, t)!,
      glow3: Color.lerp(glow3, other.glow3, t)!,
      glass: Color.lerp(glass, other.glass, t)!,
      glassStrong: Color.lerp(glassStrong, other.glassStrong, t)!,
      glassLine: Color.lerp(glassLine, other.glassLine, t)!,
      surface: Color.lerp(surface, other.surface, t)!,
      sunken: Color.lerp(sunken, other.sunken, t)!,
      ink: Color.lerp(ink, other.ink, t)!,
      inkMuted: Color.lerp(inkMuted, other.inkMuted, t)!,
      line: Color.lerp(line, other.line, t)!,
      lineStrong: Color.lerp(lineStrong, other.lineStrong, t)!,
      accent: Color.lerp(accent, other.accent, t)!,
      onAccent: Color.lerp(onAccent, other.onAccent, t)!,
      accentText: Color.lerp(accentText, other.accentText, t)!,
      success: Color.lerp(success, other.success, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      danger: Color.lerp(danger, other.danger, t)!,
      scrim: Color.lerp(scrim, other.scrim, t)!,
    );
  }
}

abstract final class PbSpace {
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s6 = 24;
  static const double s8 = 32;
}

abstract final class PbRadius {
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 20;
  static const double xl = 28;
}

abstract final class PbSize {
  static const double touchMin = 48;
  static const double actionHeight = 56;
  static const double glassBlur = 26;
  static const double glowBlur = 48;
}

abstract final class PbText {
  /// Значение, которое человек вводит прямо сейчас: вес в панели ввода результата.
  static const numHero = TextStyle(
    fontFamily: 'Fira Sans Extra Condensed',
    fontSize: 72.0,
    height: 1.000,
    fontWeight: FontWeight.w800,
    fontVariations: [FontVariation('wght', 800)],
    fontFeatures: [FontFeature.tabularFigures()],
  );

  /// Подходы и повторения в панели ввода; итог упражнения на экране тренировки.
  static const numLg = TextStyle(
    fontFamily: 'Fira Sans Extra Condensed',
    fontSize: 44.0,
    height: 1.000,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wght', 700)],
    fontFeatures: [FontFeature.tabularFigures()],
  );

  /// Факт в строке «план и факт», значения на графике прогресса.
  static const numMd = TextStyle(
    fontFamily: 'Fira Sans Extra Condensed',
    fontSize: 28.0,
    height: 1.071,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wght', 700)],
    fontFeatures: [FontFeature.tabularFigures()],
  );

  /// План в строке «план и факт», цифры в списках истории.
  static const numSm = TextStyle(
    fontFamily: 'Fira Sans Extra Condensed',
    fontSize: 20.0,
    height: 1.100,
    fontWeight: FontWeight.w600,
    fontVariations: [FontVariation('wght', 600)],
    fontFeatures: [FontFeature.tabularFigures()],
  );

  /// Заголовок экрана.
  static const title = TextStyle(
    fontFamily: 'Golos Text',
    fontSize: 26.0,
    height: 1.154,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wght', 700)],
  );

  /// Название упражнения, заголовок карточки и шторки.
  static const heading = TextStyle(
    fontFamily: 'Golos Text',
    fontSize: 20.0,
    height: 1.300,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wght', 700)],
  );

  /// Основной текст, строки списков.
  static const body = TextStyle(
    fontFamily: 'Golos Text',
    fontSize: 17.0,
    height: 1.412,
    fontWeight: FontWeight.w400,
    fontVariations: [FontVariation('wght', 400)],
  );

  /// Подпись кнопки, выделенное слово в тексте.
  static const bodyStrong = TextStyle(
    fontFamily: 'Golos Text',
    fontSize: 17.0,
    height: 1.412,
    fontWeight: FontWeight.w700,
    fontVariations: [FontVariation('wght', 700)],
  );

  /// Подписи «План», «Факт», названия полей, подписи вкладок.
  static const label = TextStyle(
    fontFamily: 'Golos Text',
    fontSize: 14.0,
    height: 1.286,
    fontWeight: FontWeight.w600,
    fontVariations: [FontVariation('wght', 600)],
    letterSpacing: 0.28,
  );

  /// Подсказки и служебные пометки.
  static const caption = TextStyle(
    fontFamily: 'Golos Text',
    fontSize: 14.0,
    height: 1.429,
    fontWeight: FontWeight.w500,
    fontVariations: [FontVariation('wght', 500)],
  );
}
