// Generates lib/design/tokens.g.dart from design/system/project/tokens.json.
// Run from the project root: dart run tool/gen_tokens.dart
import 'dart:convert';
import 'dart:io';

const _source = 'design/system/project/tokens.json';
const _target = 'lib/design/tokens.g.dart';

String _camel(String name) {
  final parts = name.split(RegExp(r'[-_.]'));
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String _color(String value) {
  final hex = RegExp(r'^#([0-9a-fA-F]{6})$').firstMatch(value);
  if (hex != null) return 'Color(0xFF${hex[1]!.toUpperCase()})';
  final rgba = RegExp(r'^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\)$')
      .firstMatch(value);
  if (rgba == null) throw FormatException('Unsupported color: $value');
  final alpha = (double.parse(rgba[4]!) * 255).round();
  final argb = [
    alpha,
    for (var i = 1; i <= 3; i++) int.parse(rgba[i]!),
  ].map((c) => c.toRadixString(16).padLeft(2, '0').toUpperCase()).join();
  return 'Color(0x$argb)';
}

String _px(Object value) => value.toString().replaceAll('px', '');

void main() {
  final tokens =
      jsonDecode(File(_source).readAsStringSync()) as Map<String, dynamic>;
  final color = tokens['color'] as Map<String, dynamic>;
  final themes = [for (final t in color['themes'] as List) t['id'] as String];
  final colors = (color['tokens'] as List).cast<Map<String, dynamic>>();
  final names = [for (final c in colors) _camel(c['name'] as String)];

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_tokens.dart from $_source.')
    ..writeln('// Do not edit by hand.')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('@immutable')
    ..writeln('class PbColors extends ThemeExtension<PbColors> {')
    ..writeln('  const PbColors({')
    ..writeAll([for (final n in names) '    required this.$n,\n'])
    ..writeln('  });')
    ..writeln();

  for (final theme in themes) {
    out.writeln('  static const $theme = PbColors(');
    for (var i = 0; i < colors.length; i++) {
      final value = (colors[i]['value'] as Map<String, dynamic>)[theme];
      out.writeln('    ${names[i]}: ${_color(value as String)},');
    }
    out
      ..writeln('  );')
      ..writeln();
  }

  for (var i = 0; i < colors.length; i++) {
    out
      ..writeln('  /// ${colors[i]['usage']}')
      ..writeln('  final Color ${names[i]};')
      ..writeln();
  }

  out
    ..writeln('  @override')
    ..writeln('  PbColors copyWith() => this;')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  PbColors lerp(PbColors? other, double t) {')
    ..writeln('    if (other == null) return this;')
    ..writeln('    return PbColors(')
    ..writeAll([
      for (final n in names) '      $n: Color.lerp($n, other.$n, t)!,\n',
    ])
    ..writeln('    );')
    ..writeln('  }')
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class PbSpace {');
  for (final t in (tokens['spacing']['tokens'] as List)) {
    out.writeln(
      '  static const double ${_camel((t['name'] as String).replaceFirst('space-', 's'))} = ${_px(t['value'])};',
    );
  }
  out
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class PbRadius {');
  for (final t in (tokens['radius']['tokens'] as List)) {
    out.writeln(
      '  static const double ${_camel((t['name'] as String).replaceFirst('radius-', ''))} = ${_px(t['value'])};',
    );
  }
  out
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class PbSize {');
  for (final t in (tokens['size']['tokens'] as List)) {
    out.writeln(
      '  static const double ${_camel(t['name'] as String)} = ${_px(t['value'])};',
    );
  }
  out
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class PbText {');
  for (final group in (tokens['type']['groups'] as List)) {
    final family = group['family'] == 'num'
        ? 'Fira Sans Extra Condensed'
        : 'Golos Text';
    for (final s in (group['styles'] as List)) {
      final size = double.parse(_px(s['fontSize']));
      final height = double.parse(_px(s['lineHeight'])) / size;
      final weight = s['fontWeight'] as int;
      final spacing = s['letterSpacing'] == null
          ? ''
          : ' letterSpacing: ${double.parse((s['letterSpacing'] as String).replaceAll('em', '')) * size},';
      final figures = group['family'] == 'num'
          ? ' fontFeatures: [FontFeature.tabularFigures()],'
          : '';
      out
        ..writeln('  /// ${s['usage']}')
        ..writeln(
          "  static const ${_camel(s['name'] as String)} = TextStyle(fontFamily: '$family', fontSize: $size, height: ${height.toStringAsFixed(3)}, fontWeight: FontWeight.w$weight, fontVariations: [FontVariation('wght', $weight)],$spacing$figures);",
        )
        ..writeln();
    }
  }
  out.writeln('}');

  File(_target)
    ..createSync(recursive: true)
    ..writeAsStringSync(out.toString());
  stdout.writeln('Wrote $_target');
}
